#!/bin/bash
# Full production database dump (including user data)
#
# Use this to create an exact replica of production for local development.
# Includes all tables: users, workouts, sessions, exercises, etc.
#
# IMPORTANT: This includes personal workout data. Only use for pre-launch
# development with your own data.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SEED_FILE="$PROJECT_ROOT/supabase/seed.sql"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}================================================"
echo "Full Production Database Dump"
echo -e "================================================${NC}"
echo ""
echo -e "${YELLOW}⚠ This will dump ALL data including:"
echo "  - User accounts and profiles"
echo "  - Workout sessions and performance data"
echo "  - Personal notes and preferences"
echo -e "${NC}"

# Check for DATABASE_URL
if [ -z "$PRODUCTION_DATABASE_URL" ]; then
    echo -e "${RED}Error: PRODUCTION_DATABASE_URL not set${NC}"
    echo ""
    echo "Get your production database URL from Supabase:"
    echo "  1. Go to Project Settings > Database"
    echo "  2. Copy the Connection String (URI)"
    echo "  3. Export it:"
    echo ""
    echo "     export PRODUCTION_DATABASE_URL='postgresql://postgres:[password]@[host]:5432/postgres'"
    echo ""
    echo "Then run this script again."
    echo ""
    exit 1
fi

# Mask password in display
DISPLAY_URL=$(echo "$PRODUCTION_DATABASE_URL" | sed 's/:[^@]*@/:***@/')
echo -e "${BLUE}Source: ${DISPLAY_URL}${NC}"
echo ""

# Check for pg_dump
if ! command -v pg_dump &> /dev/null; then
    echo -e "${RED}Error: pg_dump not found${NC}"
    echo ""
    echo "Install PostgreSQL client:"
    echo "  macOS: brew install postgresql@17"
    echo ""
    exit 1
fi

read -p "Continue with full dump? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
fi

echo ""
echo -e "${BLUE}Step 1: Dumping all production data...${NC}"

# Dump ALL data from public schema (excluding system tables)
# This gets everything: users, sessions, exercises, plans, etc.
pg_dump "$PRODUCTION_DATABASE_URL" \
    --data-only \
    --no-owner \
    --no-privileges \
    --schema=public \
    --exclude-table='supabase_migrations.schema_migrations' \
    --exclude-table='supabase_functions.migrations' \
    --column-inserts \
    > "$SEED_FILE.tmp" || {
        echo -e "${RED}✗ Dump failed${NC}"
        echo ""
        echo "Common issues:"
        echo "  - Check database URL is correct"
        echo "  - Verify network access to production"
        echo "  - Ensure password doesn't have special characters (URL encode if needed)"
        rm -f "$SEED_FILE.tmp"
        exit 1
    }

echo -e "${GREEN}✓ Data dumped${NC}"
echo ""

echo -e "${BLUE}Step 2: Creating seed file...${NC}"

# Create final seed file with header
cat > "$SEED_FILE" << 'EOF'
-- ============================================================================
-- Full Production Database Replica
-- ============================================================================
-- Generated by: database/dump_production_full.sh
--
-- This is a COMPLETE snapshot of the production database including:
--   - All user accounts and authentication data
--   - Complete workout history and performance data
--   - Plans, schedules, and exercise templates
--   - Personal notes, preferences, and metadata
--
-- This file runs automatically after migrations during `supabase db reset`
-- ============================================================================

-- Disable triggers and constraints for faster loading
SET session_replication_role = 'replica';
SET CONSTRAINTS ALL DEFERRED;

BEGIN;

-- Clean existing public tables to avoid duplicate reference data from migrations
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT schemaname, tablename
        FROM pg_tables
        WHERE schemaname = 'public'
    ) LOOP
        EXECUTE format('TRUNCATE TABLE %I.%I RESTART IDENTITY CASCADE;', r.schemaname, r.tablename);
    END LOOP;
END $$;

EOF

# Append the dumped data, filtering out psql meta-commands that start with '\'
grep -v '^\\' "$SEED_FILE.tmp" >> "$SEED_FILE"
rm -f "$SEED_FILE.tmp"

# Add footer with statistics
cat >> "$SEED_FILE" << 'EOF'

-- Re-enable normal operation
SET CONSTRAINTS ALL IMMEDIATE;
SET session_replication_role = 'origin';

COMMIT;

-- ============================================================================
-- Production Replica Statistics
-- ============================================================================
DO $$
DECLARE
    v_users INTEGER;
    v_plans INTEGER;
    v_sessions INTEGER;
    v_performed_sessions INTEGER;
    v_performed_exercises INTEGER;
    v_base_exercises INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_users FROM public.app_user;
    SELECT COUNT(*) INTO v_plans FROM public.plan;
    SELECT COUNT(*) INTO v_sessions FROM public.session_schedule;
    SELECT COUNT(*) INTO v_performed_sessions FROM public.performed_session;
    SELECT COUNT(*) INTO v_performed_exercises FROM public.performed_exercise;
    SELECT COUNT(*) INTO v_base_exercises FROM public.base_exercise;

    RAISE NOTICE '';
    RAISE NOTICE '✓ Production replica loaded successfully';
    RAISE NOTICE '================================================';
    RAISE NOTICE 'Users:                   %', v_users;
    RAISE NOTICE 'Plans:                   %', v_plans;
    RAISE NOTICE 'Session schedules:       %', v_sessions;
    RAISE NOTICE 'Base exercises:          %', v_base_exercises;
    RAISE NOTICE '------------------------------------------------';
    RAISE NOTICE 'Performed sessions:      %', v_performed_sessions;
    RAISE NOTICE 'Performed exercises:     %', v_performed_exercises;
    RAISE NOTICE '================================================';
    RAISE NOTICE '';
END $$;
EOF

echo -e "${GREEN}✓ Seed file created${NC}"
echo ""

# Show file size
FILE_SIZE=$(du -h "$SEED_FILE" | cut -f1)
LINE_COUNT=$(wc -l < "$SEED_FILE")

echo -e "${BLUE}Seed file details:${NC}"
echo "  Location: supabase/seed.sql"
echo "  Size:     $FILE_SIZE ($LINE_COUNT lines)"
echo ""

echo -e "${GREEN}================================================"
echo "Production replica ready!"
echo -e "================================================${NC}"
echo ""
echo "Next steps:"
echo "  1. Review (optional): cat supabase/seed.sql | less"
echo "  2. Apply to local:    supabase db reset"
echo ""
echo "Your local database will now match production exactly."
echo ""
