import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Plan.module.css";
import useSWR from "swr";

import { remark } from "remark";
import html from "remark-html";

import { DefaultService } from "../../src/client";
import Link from "next/link";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Typography from "@mui/material/Typography";
import { Button, CardActionArea, CardActions, Grid } from "@mui/material";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import Avatar from "@mui/material/Avatar";
import FitnessCenterIcon from "@mui/icons-material/FitnessCenter";

// TODO: Might use
async function renderHtml(text) {
  const processedContent = await remark().use(html).process(text);
  const contentHtml = processedContent.toString();
  return contentHtml;
}

const Plan: NextPage = () => {
  const router = useRouter();
  const { plan_id } = router.query;
  const { data, error } = useSWR(
    plan_id,
    DefaultService.readPlanPlansPlanIdGet
  );
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>{data?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{data?.name}</h1>

        {/* <p className={styles.description}>
          { data?.description}
        </p> */}
<Grid container spacing={{ xs: 2, md: 3 }} columns={{ xs: 1, sm: 2, md: 3 }}>
    {/* 
      <Item>xs=2</Item>
    </Grid> */}
          {data?.session_schedule?.map((session) => (
          <Grid item xs={1} sm={1} md={1} key={session.session_schedule_id}>
            <Card sx={{ maxWidth: 400 }}>
              <CardActionArea>
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    {session.name}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    {session.description}
                  </Typography>
                  <List
                    sx={{
                      width: "100%",
                      maxWidth: 360,
                      bgcolor: "background.paper",
                    }}
                  >
                    {session.exercise?.map((exercise) => (
                      <ListItem key={exercise.exercise_id}>
                        <ListItemAvatar>
                          <Avatar>
                            <FitnessCenterIcon />
                          </Avatar>
                        </ListItemAvatar>
                        <ListItemText
                          primary={exercise.base_exercise.name}
                          secondary={`${exercise.reps} ✖️ ${exercise.sets}`}
                        />
                      </ListItem>
                    ))}
                  </List>
                </CardContent>
              </CardActionArea>
              <CardActions>
                <Link href={`/session-schedule/${session.session_schedule_id}`}>
                  <Button size="small" color="primary">
                    Open
                  </Button>
                </Link>
              </CardActions>
            </Card>
</Grid>
          ))}

</Grid>

        <div className={styles.grid}>
          {data?.session_schedule?.map((session) => (
            <a
              key={session.session_schedule_id}
              href={`/session-schedule/${session.session_schedule_id}`}
              className={styles.card}
            >
              <h2>{session.name}</h2>
              <p>{session.description}</p>
              <details>
                <summary>Raw data</summary>
                <pre>{JSON.stringify(session, null, 2)}</pre>
              </details>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Plan;
