import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Plan.module.css'
import useSWR from 'swr'

import { remark } from 'remark';
import html from 'remark-html';

import { DefaultService } from '../../src/client'

// TODO: Might use
async function renderHtml(text){
  const processedContent = await remark()
    .use(html)
    .process(text);
  const contentHtml = processedContent.toString();
    return contentHtml
}

const Plan: NextPage = () => {
  const {data, error} = useSWR([0, 100], DefaultService.readPlansPlansGet)
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>

        {data?.map( plan => (
          <a key={plan.plan_id} href={`plans/${plan.plan_id}`} className={styles.card}>
            <h2>{plan.name}</h2>
            <p>{plan.description}</p>
          </a>))
        }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Plan
